package com.crossover.techtrial.controller;

import com.crossover.techtrial.dto.DailyElectricity;
import com.crossover.techtrial.model.HourlyElectricity;
import com.crossover.techtrial.model.Panel;
import com.crossover.techtrial.service.HourlyElectricityService;
import com.crossover.techtrial.service.PanelService;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * Panel Controller for all Rest APIs related to Panel.
 * @author Crossover
 *
 */

@RestController
public class PanelController {

  @Autowired
  PanelService panelService;
  
  @Autowired
  HourlyElectricityService hourlyElectricityService;
  
  /**
   * Register a Panel to System and start receiving the electricity statistics.
   * @param panel to register.
   * @return
   */
  @PostMapping(path = "/api/register")
  public ResponseEntity<?> registerPanel(@RequestBody Panel panel) {
	if (panel == null) {
		  panelService.register(panel); 
	}  
    return  ResponseEntity.accepted().build();
  }
  
  /**
   * Controller Method to save hourly Electricity to Database. 
   * @param panelSerial Serial number of Panel.
   * @param hourlyElectricity  generated electricity for this panel.
   * @return
   */
  
  @PostMapping(path = "/api/panels/{panel-serial}/hourly")
  public ResponseEntity<?> saveHourlyElectricity(
      @PathVariable(value = "panel-serial") String panelSerial, 
      @RequestBody HourlyElectricity hourlyElectricity) {
	  hourlyElectricity.setPanel(panelService.findBySerial(panelSerial)); 
	  if (hourlyElectricity.getPanel() == null) {
		  return ResponseEntity.notFound().build(); 
	  }
    return ResponseEntity.ok(hourlyElectricityService.save(hourlyElectricity));
  }
   
  /**
   * Get Hourly Electricity from Previous dates.
   */
  
  @GetMapping(path = "/api/panels/{panel-serial}/hourly")
  public ResponseEntity<?> hourlyElectricity(
      @PathVariable(value = "panel-serial") String panelSerial,
      @PageableDefault(size = 5,value = 0) Pageable pageable) {
    Panel panel = panelService.findBySerial(panelSerial);
    if (panel == null) {
      return ResponseEntity.notFound().build(); 
    }
    Page<HourlyElectricity> page = hourlyElectricityService.getAllHourlyElectricityByPanelId(
        panel.getId(), pageable);
    return ResponseEntity.ok(page);
  }
  
  /**
   * This end point is used by Front end charts component to plot the daily statistics of 
   * electricity generated by this Panel from the day it registered to end of previous day.
   * @param panelSerial is unique serial for this Panel.
   * @return
   */
  
  @GetMapping(path = "/api/panels/{panel-serial}/daily")
  public ResponseEntity<List<DailyElectricity>> allDailyElectricityFromYesterday(
      @PathVariable(value = "panel-serial") String panelSerial,
      @PageableDefault(size = 30,value = 0) Pageable pageable) {
    List<DailyElectricity> dailyElectricityForPanel = new ArrayList<>();
    LocalDate today = LocalDateTime.now().toLocalDate();
    Panel panel = panelService.findBySerial(panelSerial);
    if (panel == null) {
      return ResponseEntity.notFound().build(); 
    }
    
    Page<HourlyElectricity> page = hourlyElectricityService.getAllHourlyElectricityByPanelId(
            panel.getId(), pageable);
	List<HourlyElectricity> hours =  page.stream().filter(hourlyElectricity -> 
		hourlyElectricity.getReadingAt().toLocalDateTime()
	    .toLocalDate().isBefore(today)).collect(Collectors.toList());
	for(LocalDate hourlyIndex: hours.stream().
			map(i -> i.getReadingAt().toLocalDateTime()
					.toLocalDate()).distinct().collect(Collectors.toList())) {
		
		List<HourlyElectricity> elementsByDay = hours.stream().filter(e -> e.getReadingAt().toLocalDateTime()
				.toLocalDate().equals(hourlyIndex)).collect(Collectors.toList());
		
		double average = elementsByDay.stream().mapToDouble(n -> n.getGeneratedElectricity()).average().getAsDouble();
		long sum = elementsByDay.stream().mapToLong(n -> n.getGeneratedElectricity().intValue()).sum();
		long min = elementsByDay.stream().mapToLong(n -> n.getGeneratedElectricity().intValue()).min().getAsLong();
		long max = elementsByDay.stream().mapToLong(n -> n.getGeneratedElectricity().intValue()).max().getAsLong();
		
		dailyElectricityForPanel.add(new DailyElectricity(hourlyIndex, sum, average, min, max));
	}
	
    return ResponseEntity.ok(dailyElectricityForPanel);
  }
}